// Questions for two people awake in the dark, or for one person and Max.
// Warm, not heavy; the kind that lead somewhere.

export const TALK_PROMPTS: readonly string[] = [
  "What's the first thing you'll cook when the power's back?",
  "Who taught you to do the thing you're best at?",
  'What smell takes you straight back to being a kid?',
  'If tonight were a chapter title, what would it be?',
  'What is a small thing somebody did for you that you still remember?',
  'What would you name a boat?',
  'Tell me about the best animal you ever knew.',
  'What is a song you know every word of?',
  "What did your grandparents' house sound like?",
  "What are you good at that nobody knows about?",
  'What is the best meal you ever ate, and who was at the table?',
  'What do you want to do first when this is over?',
  'Where would you go back to tomorrow, if you could?',
  'What is the oldest thing you own?',
  'Who would you call first if the phones came back right now?',
  'What was your first job, and what did it teach you?',
  'What is a word you like the sound of?',
  'If you could fix one thing in this house properly, what would it be?',
  'What is your earliest memory of weather like this?',
  'What is a story your family tells every holiday?',
  'What did you want to be when you were ten?',
  'What is the best advice you ever ignored?',
  'What do you miss that nobody makes anymore?',
  'Which season is yours, and why?',
  'What is the last thing that made you laugh out loud?',
  'Who is the calmest person you know? What do they do that works?',
  'What is a skill you want to learn once life settles down?',
  'What is the kindest thing a stranger ever did for you?',
  'Describe your kitchen table. Who sits where?',
  'What is one thing from the last year you are quietly proud of?',
];
