// Trivia for a long night. Every answer here was written to be plainly true,
// so Max never has to make one up; she only hosts.
//
// `answers` lists every form that counts as right, lowercase. Numbers are
// digits. The checker in src/lib/nightWatch/games.ts does the forgiving.

export interface TriviaQuestion {
  q: string;
  answers: string[];
  /** Said after the answer, right or wrong. Short. */
  note?: string;
}

export const TRIVIA: readonly TriviaQuestion[] = [
  { q: 'How many legs does a spider have?', answers: ['8', 'eight'] },
  { q: 'What is the largest planet in our solar system?', answers: ['jupiter'] },
  { q: 'How many days are in a leap year?', answers: ['366'] },
  { q: 'What gas do plants take in from the air?', answers: ['carbon dioxide', 'co2'] },
  { q: 'Which planet is the hottest?', answers: ['venus'], note: 'Closer to the Sun than Venus is Mercury, but Venus is wrapped in a blanket of cloud that holds the heat.' },
  { q: 'How many strings does a standard guitar have?', answers: ['6', 'six'] },
  { q: 'What is the capital of Texas?', answers: ['austin'] },
  { q: 'How many sides does a hexagon have?', answers: ['6', 'six'] },
  { q: 'What is the chemical formula for water?', answers: ['h2o'] },
  { q: 'Which ocean is the largest?', answers: ['pacific', 'the pacific', 'pacific ocean'] },
  { q: 'What is the largest animal that has ever lived?', answers: ['blue whale', 'the blue whale', 'whale'] },
  { q: 'How many hours are in a week?', answers: ['168'] },
  { q: 'What do bees make?', answers: ['honey'] },
  { q: 'At what temperature does water freeze, in Fahrenheit?', answers: ['32', '32 degrees'] },
  { q: 'At what temperature does water boil at sea level, in Fahrenheit?', answers: ['212', '212 degrees'] },
  { q: 'How many bones are in an adult human body?', answers: ['206'] },
  { q: 'What color do you get when you mix blue and yellow?', answers: ['green'] },
  { q: 'What is the tallest animal in the world?', answers: ['giraffe', 'the giraffe'] },
  { q: 'How many minutes are in a day?', answers: ['1440', '1,440'] },
  { q: 'Which planet is called the Red Planet?', answers: ['mars'] },
  { q: 'How many players does a baseball team have on the field at once?', answers: ['9', 'nine'] },
  { q: 'What is the smallest U.S. state by area?', answers: ['rhode island'] },
  { q: 'What is the largest U.S. state by area?', answers: ['alaska'] },
  { q: 'What is the money of Japan called?', answers: ['yen', 'the yen'] },
  { q: 'How many continents are there?', answers: ['7', 'seven'] },
  { q: 'What is the hardest natural substance?', answers: ['diamond', 'diamonds'] },
  { q: 'What is the largest hot desert in the world?', answers: ['sahara', 'the sahara', 'sahara desert'] },
  { q: 'How many teeth does an adult usually have, wisdom teeth included?', answers: ['32'] },
  { q: 'What does a caterpillar turn into?', answers: ['butterfly', 'a butterfly', 'moth', 'a moth', 'butterfly or moth'] },
  { q: 'How many zeros are in one million?', answers: ['6', 'six'] },
  { q: 'What is the name of our galaxy?', answers: ['milky way', 'the milky way'] },
  { q: 'What is the main ingredient in guacamole?', answers: ['avocado', 'avocados'] },
  { q: 'How many keys does a full-size piano have?', answers: ['88'] },
  { q: 'Which bird is the national bird of the United States?', answers: ['bald eagle', 'the bald eagle', 'eagle'] },
  { q: 'What is the largest organ of the human body?', answers: ['skin', 'the skin'] },
  { q: 'What is the first element on the periodic table?', answers: ['hydrogen'] },
  { q: 'What is the capital of Canada?', answers: ['ottawa'] },
  { q: 'What is the fastest land animal?', answers: ['cheetah', 'the cheetah'] },
  { q: 'How many stripes are on the flag of the United States?', answers: ['13', 'thirteen'] },
  { q: 'How many stars are on the flag of the United States?', answers: ['50', 'fifty'] },
  { q: 'What is a baby kangaroo called?', answers: ['joey', 'a joey'] },
  { q: 'What is a group of lions called?', answers: ['pride', 'a pride'] },
  { q: 'What is the largest bird in the world?', answers: ['ostrich', 'the ostrich'] },
  { q: 'How many sides does a stop sign have?', answers: ['8', 'eight'] },
  { q: 'Which planet has the biggest, brightest rings?', answers: ['saturn'] },
  { q: 'What is the closest star to Earth?', answers: ['sun', 'the sun'] },
  { q: 'How many quarts are in a gallon?', answers: ['4', 'four'] },
  { q: 'How many ounces are in a pound?', answers: ['16', 'sixteen'] },
  { q: 'How many feet are in a mile?', answers: ['5280', '5,280'] },
  { q: 'What is the tallest mountain on Earth, measured from sea level?', answers: ['everest', 'mount everest', 'mt everest', 'mt. everest'] },
  { q: 'What do we call an animal that eats only plants?', answers: ['herbivore', 'a herbivore', 'an herbivore', 'herbivores'] },
  { q: 'How many months have 31 days?', answers: ['7', 'seven'] },
  { q: 'Which month has the fewest days?', answers: ['february'] },
  { q: 'What is the most populous U.S. state?', answers: ['california'] },
  { q: 'How many inches are in a foot?', answers: ['12', 'twelve'] },
  { q: 'What do you call a shape with three sides?', answers: ['triangle', 'a triangle'] },
  { q: 'Which fruit is dried to make raisins?', answers: ['grapes', 'grape', 'the grape'] },
  { q: 'What is the largest land animal alive today?', answers: ['elephant', 'african elephant', 'the elephant', 'the african elephant'] },
  { q: 'What do you call a doctor who treats animals?', answers: ['vet', 'veterinarian', 'a vet', 'a veterinarian'] },
  { q: 'How many legs does an insect have?', answers: ['6', 'six'] },
  { q: 'What is the Earth\'s natural satellite?', answers: ['moon', 'the moon'] },
  { q: 'How many hearts does an octopus have?', answers: ['3', 'three'] },
  { q: 'Which continent is the coldest?', answers: ['antarctica'] },
  { q: 'How many wheels does a tricycle have?', answers: ['3', 'three'] },
  { q: 'What is frozen water called?', answers: ['ice'] },
];
