// Master Content Map, ported from the planning artifact.
// status: how well-sourced the guidance is. priority: how time-critical it is.
export type ArticleStatus = "verified" | "specialist" | "partial" | "pending" | "new";
export type Priority = "P0" | "P1" | "P2" | "P3";

export interface Topic {
  title: string;
  status: ArticleStatus;
  priority: Priority;
  note: string;
}

export interface Category {
  name: string;
  note?: string;
  topics: Topic[];
}

export const CATEGORIES: Category[] = [
  {
    name: "What To Do In An Emergency",
    note: "Quick numbered-step versions of the full articles below.",
    topics: [
      { title: "Severe bleeding (tourniquet)", status: "specialist", priority: "P0", note: "Full article drafted" },
      { title: "Not breathing / cardiac arrest (CPR/AED)", status: "specialist", priority: "P0", note: "Full article drafted" },
      { title: "Choking", status: "specialist", priority: "P0", note: "2025 guidance drafted" },
      { title: "Unconscious, breathing, cause unknown", status: "specialist", priority: "P0", note: "AHA + American Red Cross" },
      { title: "Poisoning (swallowed/inhaled/skin/eye)", status: "verified", priority: "P0", note: "" },
      { title: "Burn (thermal/chemical)", status: "specialist", priority: "P0", note: "" },
      { title: "Severe allergic reaction / epinephrine", status: "specialist", priority: "P0", note: "" },
      { title: "Heart-attack symptoms / aspirin boundary", status: "specialist", priority: "P0", note: "" },
      { title: "Stroke symptoms", status: "specialist", priority: "P0", note: "" },
      { title: "Broken bone / fracture", status: "specialist", priority: "P0", note: "Full article drafted" },
      { title: "Hypothermia", status: "verified", priority: "P0", note: "Shows the full Hypothermia recognition and first aid article (Wilderness Medical Society + CDC)" },
      { title: "Heat illness (exhaustion/stroke)", status: "verified", priority: "P0", note: "Shows the full Extreme heat illness article (CDC/NIOSH + AHA/Red Cross)" },
      { title: "Animal emergency (poisoning)", status: "specialist", priority: "P0", note: "" },
      { title: "Emergency childbirth", status: "specialist", priority: "P0", note: "Shows the full Emergency childbirth and newborn care article" },
      { title: "Seizure", status: "specialist", priority: "P0", note: "" },
      { title: "Drowning / near-drowning rescue", status: "specialist", priority: "P0", note: "AHA CPR Guidelines (drowning protocol)" },
      { title: "Active violence (run-hide-fight quick card)", status: "new", priority: "P1", note: "See Security & Safety" },
      { title: "Structure fire — get out now", status: "verified", priority: "P0", note: "NFPA" },
    ],
  },
  {
    name: "Medical & First Aid",
    topics: [
      { title: "Scene safety and triage order", status: "specialist", priority: "P0", note: "" },
      { title: "Adult CPR/AED", status: "specialist", priority: "P0", note: "" },
      { title: "Pediatric/infant CPR and choking", status: "specialist", priority: "P0", note: "2025 AHA/AAP guidelines" },
      { title: "Adult choking, 2025 sequence", status: "specialist", priority: "P0", note: "" },
      { title: "Severe bleeding and tourniquet", status: "specialist", priority: "P0", note: "" },
      { title: "Junctional bleeding and wound packing", status: "specialist", priority: "P0", note: "TCCC/CoTCCC military standard" },
      { title: "Wound irrigation and when not to close", status: "specialist", priority: "P0", note: "" },
      { title: "Thermal burns", status: "specialist", priority: "P0", note: "" },
      { title: "Chemical and electrical burns", status: "specialist", priority: "P0", note: "AHA/Red Cross + OSHA" },
      { title: "Fractures, splints, circulation checks", status: "specialist", priority: "P0", note: "American Red Cross" },
      { title: "Head, neck and spinal injury", status: "specialist", priority: "P0", note: "American Red Cross" },
      { title: "Chest and abdominal trauma (open chest wound)", status: "specialist", priority: "P0", note: "" },
      { title: "Shock and hypothermia prevention (medical)", status: "specialist", priority: "P0", note: "American Red Cross + CoTCCC" },
      { title: "Emergency childbirth and newborn care", status: "specialist", priority: "P0", note: "ACOG + Red Cross Wilderness and Remote First Aid" },
      { title: "Severe allergic reaction / epinephrine", status: "specialist", priority: "P0", note: "" },
      { title: "Anaphylaxis when no epinephrine is available", status: "verified", priority: "P0", note: "ASCIA + AAAAI/ACAAI" },
      { title: "Mild allergic reaction or hives without antihistamine", status: "verified", priority: "P2", note: "ACAAI + AAD" },
      { title: "Asthma, COPD, breathing distress", status: "specialist", priority: "P0", note: "2024 AHA/Red Cross" },
      { title: "Diabetes, insulin interruption, hypoglycemia", status: "specialist", priority: "P0", note: "" },
      { title: "Seizure", status: "specialist", priority: "P0", note: "" },
      { title: "Stroke", status: "specialist", priority: "P0", note: "" },
      { title: "Heart attack and aspirin boundaries", status: "specialist", priority: "P0", note: "" },
      { title: "Dehydration and oral rehydration", status: "partial", priority: "P1", note: "" },
      { title: "Fever, respiratory infection, isolation", status: "specialist", priority: "P1", note: "" },
      { title: "Sepsis warning signs", status: "specialist", priority: "P1", note: "CDC + Sepsis Alliance" },
      { title: "Dental pain, broken tooth, facial swelling", status: "verified", priority: "P1", note: "ADA/MouthHealthy + JADA" },
      { title: "Eye injury and chemical irrigation", status: "verified", priority: "P0", note: "AAO + Mayo Clinic" },
      { title: "Smoke inhalation and carbon monoxide", status: "specialist", priority: "P0", note: "CDC" },
      { title: "Snakebite and venomous arthropods (human)", status: "specialist", priority: "P0", note: "CDC/Red Cross/Mayo" },
      { title: "Tick bite, rabies exposure, animal bite (human)", status: "specialist", priority: "P1", note: "CDC rabies PEP guidance" },
      { title: "Dog/animal bite wound care and infection risk", status: "verified", priority: "P1", note: "CDC" },
      { title: "Ankle sprain / twisted ankle", status: "verified", priority: "P3", note: "Mayo Clinic + AAOS" },
      { title: "Unknown swallowed poison, no induced vomiting", status: "verified", priority: "P0", note: "" },
      { title: "Poison exposure by eye, skin, inhalation", status: "verified", priority: "P0", note: "" },
      { title: "Activated-charcoal limitations (human)", status: "verified", priority: "P0", note: "" },
      { title: "Opioid overdose and naloxone", status: "specialist", priority: "P0", note: "" },
      { title: "Non-opioid medication overdose", status: "verified", priority: "P0", note: "Poison Control 1-800-222-1222" },
      { title: "Wild plant/mushroom poisoning (human)", status: "verified", priority: "P0", note: "Poison Control + CA Poison Control" },
      { title: "Pesticide exposure", status: "specialist", priority: "P1", note: "EPA" },
      { title: "Medication storage, expiration, continuity", status: "verified", priority: "P1", note: "" },
      { title: "Poison-record log (substance/amount/time/symptoms)", status: "partial", priority: "P2", note: "" },
      { title: "Cold-water immersion and drowning rescue", status: "specialist", priority: "P0", note: "Wilderness Medical Society + AHA" },
      { title: "Femur fracture: making a traction splint", status: "partial", priority: "P0", note: "" },
      { title: "Broken facial bones and airway protection", status: "partial", priority: "P0", note: "" },
      { title: "Choking when you're alone (self-rescue)", status: "partial", priority: "P0", note: "" },
      { title: "Impaled object: never pull it out", status: "partial", priority: "P0", note: "" },
      { title: "Abdominal evisceration: organs exposed", status: "partial", priority: "P0", note: "" },
      { title: "Blunt internal bleeding recognition", status: "partial", priority: "P0", note: "" },
      { title: "Cellulitis: red streaks spreading from a wound", status: "partial", priority: "P1", note: "" },
      { title: "Severe nosebleeds that won't stop", status: "partial", priority: "P2", note: "" },
      { title: "Black widow, brown recluse, and scorpion stings", status: "partial", priority: "P1", note: "" },
      { title: "Emergency tooth extraction (true last resort only)", status: "partial", priority: "P2", note: "" },
      { title: "Crush syndrome: why timing matters before freeing a trapped limb", status: "partial", priority: "P1", note: "" },
      { title: "Blast injury: lung and ear trauma", status: "partial", priority: "P1", note: "" },
      { title: "High-altitude sickness: AMS, HAPE, and HACE", status: "specialist", priority: "P0", note: "Wilderness Medical Society" },
      { title: "Improvised hot and cold packs", status: "partial", priority: "P3", note: "" },
    ],
  },
  {
    name: "Disasters",
    topics: [
      { title: "Tornado warning shelter", status: "verified", priority: "P1", note: "NOAA/NSSL + FEMA" },
      { title: "Hurricane watch/warning/evacuation", status: "verified", priority: "P1", note: "NOAA/NHC + Ready.gov/FEMA" },
      { title: "Storm surge evacuation", status: "verified", priority: "P1", note: "NOAA NHC Storm Surge Unit + FEMA" },
      { title: "River / prolonged inland flood", status: "verified", priority: "P1", note: "Ready.gov/FEMA + NWS" },
      { title: "Flash flood", status: "verified", priority: "P0", note: "NOAA/NWS + FEMA" },
      { title: "Driving into flood water (Turn Around, Don't Drown)", status: "verified", priority: "P0", note: "NWS + FEMA + CDC" },
      { title: "Severe thunderstorm, straight-line wind, hail", status: "verified", priority: "P1", note: "NWS" },
      { title: "Lightning", status: "verified", priority: "P0", note: "NOAA/NWS" },
      { title: "Winter storm, blizzard, ice storm", status: "verified", priority: "P1", note: "CDC + Ready.gov" },
      { title: "Extreme heat illness", status: "verified", priority: "P0", note: "CDC/NIOSH + AHA/Red Cross" },
      { title: "Wildfire warning, evacuation, smoke", status: "verified", priority: "P1", note: "NFPA Firewise USA + Ready.gov/FEMA" },
      { title: "Earthquake shaking and aftershocks", status: "verified", priority: "P1", note: "USGS + Ready.gov/FEMA" },
      { title: "Landslide and mudflow", status: "verified", priority: "P1", note: "USGS + CDC" },
      { title: "Dam or levee failure", status: "partial", priority: "P1", note: "FEMA" },
      { title: "Tsunami", status: "verified", priority: "P0", note: "NOAA/NWS" },
      { title: "Drought and prolonged water shortage", status: "partial", priority: "P2", note: "NOAA NIDIS + USGS" },
      { title: "Volcanic ash", status: "verified", priority: "P2", note: "USGS Volcano Hazards Program" },
      { title: "Natural-gas or propane odor", status: "verified", priority: "P0", note: "NFPA 54 + American Gas Association" },
      { title: "Carbon-monoxide alarm or symptoms (general)", status: "verified", priority: "P0", note: "NFPA" },
      { title: "Chemical plume: evacuate or shelter", status: "verified", priority: "P0", note: "US DOT PHMSA + FEMA" },
      { title: "Unknown industrial smoke or fire", status: "verified", priority: "P0", note: "PHMSA/Mass.gov" },
      { title: "Train/truck hazardous-material release", status: "verified", priority: "P0", note: "PHMSA Emergency Response Guidebook" },
      { title: "Nuclear detonation flash/blast/fallout", status: "verified", priority: "P0", note: "CDC" },
      { title: "Dirty bomb vs. nuclear explosion distinction", status: "verified", priority: "P0", note: "CDC" },
      { title: "Radiation shelter and decontamination", status: "verified", priority: "P0", note: "CDC" },
      { title: "Biological outbreak and household isolation", status: "verified", priority: "P0", note: "CDC" },
      { title: "Aircraft impact/explosion in a building", status: "verified", priority: "P1", note: "NFPA + FEMA" },
      { title: "Caught in an avalanche", status: "partial", priority: "P1", note: "" },
      { title: "Escaping quicksand, mudflats, and saturated silt", status: "partial", priority: "P2", note: "" },
      { title: "Advanced home isolation: negative-pressure room and PPE routine", status: "partial", priority: "P2", note: "" },
      { title: "Trapped in a building collapse: what to do until help arrives", status: "partial", priority: "P1", note: "" },
      { title: "Anhydrous ammonia leak", status: "partial", priority: "P1", note: "" },
      { title: "Fuel spill containment (gasoline/diesel)", status: "partial", priority: "P2", note: "" },
    ],
  },
  {
    name: "Water",
    topics: [
      { title: "Emergency stored-water quantity and containers", status: "verified", priority: "P0", note: "" },
      { title: "Tap water suspected unsafe", status: "verified", priority: "P0", note: "" },
      { title: "Boiling for microbial hazards", status: "verified", priority: "P0", note: "" },
      { title: "Concentration-aware household bleach treatment", status: "verified", priority: "P0", note: "" },
      { title: "Portable filter limits", status: "verified", priority: "P0", note: "" },
      { title: "Emergency household water sources", status: "verified", priority: "P1", note: "" },
      { title: "Flooded private well, initial response", status: "verified", priority: "P0", note: "" },
      { title: "Hot-water tank safe isolation and draining", status: "specialist", priority: "P1", note: "CDC + FEMA — involves electrical/gas shutoff" },
      { title: "Household pipe gravity draining", status: "partial", priority: "P2", note: "" },
      { title: "Rainwater collection and first-flush contamination", status: "verified", priority: "P1", note: "CDC + Texas A&M AgriLife Extension" },
      { title: "Saltwater/brackish desalination limits", status: "partial", priority: "P2", note: "" },
      { title: "Chemical/fuel/algal-toxin/radiological rejection", status: "verified", priority: "P0", note: "EPA + CDC WASH" },
      { title: "UV purification methods (e.g. SODIS, UV pens)", status: "verified", priority: "P1", note: "WHO + CDC" },
      { title: "Water testing without a lab: turbidity, smell, and color", status: "partial", priority: "P1", note: "" },
    ],
  },
  {
    name: "Food",
    topics: [
      { title: "Refrigerator/freezer outage timing", status: "verified", priority: "P1", note: "CDC + FoodSafety.gov" },
      { title: "Flood-contaminated food and container salvage", status: "verified", priority: "P0", note: "USDA/FSIS" },
      { title: "Damaged/bulging/rusted cans", status: "verified", priority: "P0", note: "USDA/FSIS" },
      { title: "Manual can opening and injury control", status: "partial", priority: "P2", note: "Commonsense practical safety only" },
      { title: "Outdoor stove, grill, and fire cooking", status: "verified", priority: "P1", note: "CPSC/NFPA" },
      { title: "Safe cooking temperatures", status: "verified", priority: "P1", note: "FoodSafety.gov" },
      { title: "Cross-contamination without running water", status: "verified", priority: "P1", note: "CDC/FSIS" },
      { title: "Infant feeding without safe water or refrigeration", status: "verified", priority: "P0", note: "CDC" },
      { title: "Dry staples, rationing, special diets", status: "verified", priority: "P2", note: "Ready.gov/FEMA + UGA Extension" },
      { title: "Thawing, refreezing, ice-crystal rule", status: "verified", priority: "P1", note: "CDC/FoodSafety.gov" },
      { title: "Dry ice ventilation and handling", status: "verified", priority: "P1", note: "Cornell EHS + NIH ORS" },
      { title: "Retained-heat cooking, low-fuel", status: "partial", priority: "P1", note: "Haybox technique" },
      { title: "Food dehydration and humidity limits", status: "verified", priority: "P2", note: "NCHFP + USDA" },
      { title: "Water-bath vs. pressure canning", status: "verified", priority: "P0", note: "CDC + NCHFP" },
      { title: "Botulism warning signs and disposal", status: "verified", priority: "P0", note: "CDC" },
      { title: "Rodent/insect contamination", status: "verified", priority: "P1", note: "FDA" },
      { title: "Wild game handling and cooking", status: "verified", priority: "P1", note: "USDA FSIS + CDC" },
      { title: "Fish toxins and harmful algal blooms", status: "partial", priority: "P0", note: "" },
      { title: "Food rotation / FIFO principles", status: "partial", priority: "P3", note: "" },
    ],
  },
  {
    name: "Shelter & Heat",
    topics: [
      { title: "Tornado warning shelter", status: "verified", priority: "P1", note: "NOAA/NSSL + FEMA" },
      { title: "Lightning shelter", status: "verified", priority: "P0", note: "" },
      { title: "Heat exhaustion and heat stroke", status: "verified", priority: "P0", note: "" },
      { title: "Wildfire smoke clean room", status: "verified", priority: "P1", note: "EPA + CDC" },
      { title: "Structure fire escape", status: "verified", priority: "P0", note: "" },
      { title: "Gas or propane odor", status: "verified", priority: "P0", note: "" },
      { title: "Carbon-monoxide alarm or symptoms", status: "specialist", priority: "P0", note: "CDC + NFPA 720" },
      { title: "Winter outage and safe-room selection", status: "verified", priority: "P1", note: "American Red Cross + CDC" },
      { title: "Hypothermia recognition and first aid", status: "verified", priority: "P0", note: "Wilderness Medical Society + CDC" },
      { title: "Trench foot (feet wet and cold for too long)", status: "partial", priority: "P2", note: "" },
      { title: "Active chimney or flue fire", status: "partial", priority: "P1", note: "" },
      { title: "Frostbite and refreezing risk", status: "verified", priority: "P0", note: "Wilderness Medical Society" },
      { title: "Extreme-heat home cooling without power", status: "verified", priority: "P0", note: "CDC + FEMA" },
      { title: "Safe indoor lighting during blackout", status: "verified", priority: "P1", note: "NFPA + FEMA" },
      { title: "Fireplace/chimney limitations before use", status: "verified", priority: "P0", note: "CSIA + NFPA 211" },
      { title: "Wood-stove and combustion-heater safety", status: "verified", priority: "P0", note: "NFPA 211" },
      { title: "Outdoor cooking placement and fire control", status: "verified", priority: "P1", note: "CPSC + NFPA 58" },
      { title: "Campfire site and extinguishment", status: "verified", priority: "P1", note: "USFS + Scouting America" },
      { title: "Wildland fire ignition restrictions", status: "verified", priority: "P1", note: "USFS + BLM" },
      { title: "Temporary shelter and ventilation", status: "verified", priority: "P1", note: "US Army FM 21-76 + FEMA" },
      { title: "Damaged roof, windows, weatherproofing", status: "verified", priority: "P2", note: "FEMA + NRCA" },
      { title: "Fire without a lighter (ferro rod, steel wool, friction)", status: "verified", priority: "P2", note: "U.S. Army Survival Manual — safety-reviewed" },
      { title: "Improvised skillet-support / cook-fire rig", status: "verified", priority: "P2", note: "US Forest Service + BSA — stability-reviewed" },
      { title: "Safe indoor kerosene heater maintenance and wick trimming", status: "partial", priority: "P2", note: "" },
    ],
  },
  {
    name: "Power & Lighting",
    topics: [
      { title: "General power outage", status: "verified", priority: "P1", note: "American Red Cross + CDC" },
      { title: "Generator carbon-monoxide safety", status: "verified", priority: "P0", note: "US CPSC + NFPA" },
      { title: "Generator electrical connection / backfeed prevention", status: "verified", priority: "P0", note: "Safe Electricity + NEC" },
      { title: "Downed power lines and electrified water", status: "verified", priority: "P0", note: "ESFI + utility companies" },
      { title: "Appliance reconnection and surge risk", status: "partial", priority: "P1", note: "" },
      { title: "Solar panel, charge controller, power-bank chain", status: "partial", priority: "P2", note: "Morningstar" },
      { title: "Lithium battery heat/cold/fire/storage", status: "verified", priority: "P1", note: "CPSC + NY State DHSES" },
      { title: "Vehicle charging without CO exposure", status: "verified", priority: "P0", note: "NFPA" },
      { title: "Phone low-power settings and battery budgeting", status: "verified", priority: "P2", note: "Ready.gov/FEMA + FCC + DOE" },
      { title: "Suspected EMP: what can/cannot be inferred", status: "verified", priority: "P3", note: "CISA/DHS/FEMA" },
      { title: "Battery watt-hour budgeting (calculator)", status: "verified", priority: "P2", note: "NEC Article 690/706 + DOE" },
      { title: "Emergency candle and lamp making (animal tallow and plant oils)", status: "verified", priority: "P3", note: "Penn State Extension" },
      { title: "Faraday protection for radios and electronics", status: "partial", priority: "P3", note: "" },
      { title: "Freeing someone from a live household electrical source", status: "partial", priority: "P0", note: "" },
      { title: "Generator maintenance: oil, spark plugs, carburetor", status: "partial", priority: "P2", note: "" },
      { title: "Battery care and revival (lead-acid and AGM)", status: "partial", priority: "P2", note: "" },
    ],
  },
  {
    name: "Home Systems",
    topics: [
      { title: "Water, electricity, gas, propane shutoffs", status: "verified", priority: "P1", note: "Ready.gov/FEMA" },
      { title: "Electrical panel and de-energizing verification", status: "specialist", priority: "P0", note: "NFPA 70E + OSHA — flagged for qualified review" },
      { title: "Broken water pipe isolation and temp patch", status: "verified", priority: "P1", note: "American Red Cross + FEMA" },
      { title: "Frozen pipe prevention and thawing", status: "verified", priority: "P1", note: "American Red Cross" },
      { title: "Sewage backup", status: "verified", priority: "P1", note: "CDC + EPA" },
      { title: "Septic failure", status: "verified", priority: "P1", note: "CDC + EPA" },
      { title: "Roof leak and temporary tarp", status: "verified", priority: "P1", note: "FEMA + FLASH" },
      { title: "Structural damage and unsafe-building signs", status: "verified", priority: "P1", note: "FEMA + ATC-20" },
      { title: "Well power and pressure system", status: "partial", priority: "P1", note: "" },
      { title: "Sump-pump failure", status: "verified", priority: "P2", note: "FEMA" },
      { title: "Water-heater isolation", status: "specialist", priority: "P1", note: "CDC + Ready.gov/FEMA — involves electrical/gas shutoff" },
      { title: "Appliance failure and safe restart", status: "partial", priority: "P2", note: "" },
      { title: "High-wind window hardening (plywood vs. duct tape)", status: "partial", priority: "P1", note: "" },
      { title: "Running propane safely to an indoor-rated appliance", status: "partial", priority: "P1", note: "" },
      { title: "Shoring a sagging ceiling or damaged wall", status: "partial", priority: "P1", note: "" },
      { title: "Managing wet crawlspaces and basement flooding", status: "partial", priority: "P2", note: "" },
    ],
  },
  {
    name: "Vehicles & Mechanics",
    topics: [
      { title: "Tire change and roadside visibility", status: "partial", priority: "P1", note: "NHTSA stats" },
      { title: "Tire puncture limits and plug boundaries", status: "verified", priority: "P2", note: "NHTSA + Tire Industry Association" },
      { title: "Jump-start sequence by vehicle type", status: "verified", priority: "P1", note: "AAA standard sequence" },
      { title: "Electric/hybrid vehicle crash and flood hazards", status: "verified", priority: "P0", note: "NFPA + NHTSA" },
      { title: "Vehicle submersion: escaping a sinking car", status: "verified", priority: "P0", note: "AAA + Kids and Car Safety" },
      { title: "Vehicle overheating", status: "partial", priority: "P1", note: "AAA" },
      { title: "Vehicle stranded in heat or cold", status: "verified", priority: "P0", note: "CDC + Ready.gov/FEMA + AAA + AZDOT" },
      { title: "Hit an animal with your car (deer/wildlife strike)", status: "verified", priority: "P2", note: "PennDOT + PA Insurance Dept + Michigan State Police" },
      { title: "Fuel storage, transfer, fire safety", status: "verified", priority: "P0", note: "NFPA 30/30A + CPSC" },
      { title: "Small-engine troubleshooting", status: "partial", priority: "P2", note: "Generac official troubleshooting guide" },
      { title: "Chainsaw and cutting-tool safety", status: "specialist", priority: "P1", note: "OSHA + CDC/NIOSH" },
      { title: "Manual siphon-pump legal/safety boundaries", status: "verified", priority: "P2", note: "CDC + CPSC" },
      { title: "Immediate steps after a car crash", status: "verified", priority: "P1", note: "US DOT + NHTSA" },
      { title: "Spark-plug inspection/replacement", status: "partial", priority: "P2", note: "Closed by the small-engine troubleshooting research (Generac guide)" },
      { title: "Emergency vehicle extraction (tow straps, winching, traction)", status: "specialist", priority: "P2", note: "NORA + SAE" },
      { title: "Emergency vehicle maintenance (fluid leaks, belts, tires)", status: "verified", priority: "P2", note: "DOT + SAE" },
    ],
  },
  {
    name: "Animals & Pets",
    topics: [
      { title: "Unknown pet poison response", status: "specialist", priority: "P0", note: "ASPCA + Merck Veterinary Manual" },
      { title: "Dog/cat NSAID and acetaminophen boundaries", status: "specialist", priority: "P0", note: "FDA Center for Veterinary Medicine + ASPCA" },
      { title: "Pet evacuation kit and records", status: "verified", priority: "P2", note: "FEMA/Red Cross + AVMA" },
      { title: "Veterinary activated-charcoal decision boundary", status: "specialist", priority: "P0", note: "ACVECC + Merck Veterinary Manual" },
      { title: "Milk thistle/silymarin evidence and limits", status: "specialist", priority: "P1", note: "Plumb's Veterinary Drug Handbook + ASPCA" },
      { title: "Dog xylitol exposure", status: "specialist", priority: "P0", note: "FDA + AAHA" },
      { title: "Cat true-lily exposure", status: "specialist", priority: "P0", note: "FDA + ASPCA" },
      { title: "Common toxic foods (pets)", status: "specialist", priority: "P0", note: "ASPCA + Merck Veterinary Manual" },
      { title: "Dog heatstroke", status: "specialist", priority: "P0", note: "JAVMA + BSAVA — cool-first, transport-second" },
      { title: "Cat-specific heatstroke", status: "specialist", priority: "P0", note: "RVC + PDSA — gradual cooling only" },
      { title: "Pet hypothermia and frostbite", status: "specialist", priority: "P0", note: "American Red Cross Pet First Aid" },
      { title: "Pet trauma, bleeding, fractures, safe transport", status: "specialist", priority: "P0", note: "AVMA + Merck Veterinary Manual" },
      { title: "Bloat/GDV warning signs", status: "specialist", priority: "P0", note: "AAHA — no safe home treatment" },
      { title: "Pet seizure and breathing distress", status: "specialist", priority: "P0", note: "AVMA + PDSA" },
      { title: "Pet snakebite and envenomation", status: "verified", priority: "P0", note: "Merck Veterinary Manual + VCA" },
      { title: "Contaminated coat/skin decontamination", status: "specialist", priority: "P1", note: "ASPCA + Merck Veterinary Manual" },
      { title: "Wild animal encounter: bears (black vs. grizzly)", status: "verified", priority: "P1", note: "National Park Service" },
      { title: "Wild animal encounter: mountain lion/cougar", status: "verified", priority: "P1", note: "US Fish & Wildlife Service + NPS" },
      { title: "Wild animal encounter: coyote", status: "verified", priority: "P2", note: "San Diego Humane Society" },
      { title: "Wild animal encounter: alligator", status: "verified", priority: "P1", note: "Florida FWC" },
      { title: "Wild animal encounter: snake (avoidance, not bite treatment)", status: "verified", priority: "P1", note: "CDC/NIOSH + US Army" },
      { title: "Wildlife displaced by disaster (general principle)", status: "verified", priority: "P2", note: "Texas Parks & Wildlife" },
      { title: "Livestock water, feed, evacuation", status: "verified", priority: "P1", note: "USDA FSA" },
      { title: "Downed fences and escaped animals", status: "partial", priority: "P1", note: "MU/OSU Extension" },
      { title: "Carcass handling and zoonotic disease", status: "verified", priority: "P1", note: "CDC + USDA APHIS" },
      { title: "Aggressive dog attack defense", status: "partial", priority: "P1", note: "" },
      { title: "Dog or cat choking", status: "partial", priority: "P1", note: "" },
      { title: "Livestock bloat: recognizing it and what you can safely do", status: "partial", priority: "P1", note: "" },
      { title: "Livestock fracture management (large animals)", status: "partial", priority: "P2", note: "" },
    ],
  },
  {
    name: "Communication",
    topics: [
      { title: "No cellular service or internet", status: "verified", priority: "P1", note: "FCC/FEMA" },
      { title: "NOAA Weather Radio", status: "verified", priority: "P1", note: "NOAA/NWS" },
      { title: "AM/FM emergency broadcasts", status: "verified", priority: "P1", note: "FEMA IPAWS/EAS" },
      { title: "FRS, GMRS, MURS, CB, amateur-radio boundaries", status: "verified", priority: "P2", note: "47 CFR Part 95/97" },
      { title: "Texting vs. calling during network congestion", status: "partial", priority: "P2", note: "" },
      { title: "Family communication plan and rendezvous points", status: "verified", priority: "P1", note: "Ready.gov/FEMA + American Red Cross" },
      { title: "Paper maps, contacts, critical records backup", status: "partial", priority: "P2", note: "" },
      { title: "Emergency alert verification and rumor control", status: "verified", priority: "P1", note: "FEMA Rumor Response" },
      { title: "Amateur (ham) radio licensing basics", status: "partial", priority: "P3", note: "" },
    ],
  },
  {
    name: "Navigation",
    topics: [
      { title: "Reading a paper/topographic map", status: "verified", priority: "P2", note: "FM 3-25.26 (US Army)" },
      { title: "Compass use and orientation", status: "verified", priority: "P2", note: "FM 3-25.26 + MSU Extension" },
      { title: "Land navigation without GPS", status: "verified", priority: "P2", note: "FM 3-25.26" },
      { title: "Downloading and using offline map packs", status: "verified", priority: "P2", note: "Built: Offline Maps screen. OpenStreetMap via OpenFreeMap" },
      { title: "Identifying safe vs. unsafe routes during a disaster", status: "verified", priority: "P1", note: "Ready.gov/FEMA" },
      { title: "Finding cardinal directions without a compass", status: "verified", priority: "P3", note: "FM 3-25.26 Appendix F" },
      { title: "Marking private landmarks/hazards on offline maps", status: "partial", priority: "P3", note: "" },
      { title: "Wilderness signaling and search-and-rescue marking", status: "verified", priority: "P2", note: "NASAR + USAF AFMAN 10-503" },
      { title: "Lost in the woods: what to do first", status: "partial", priority: "P1", note: "" },
      { title: "Lost in an unfamiliar city on foot", status: "partial", priority: "P2", note: "" },
      { title: "Lost while driving in a city", status: "partial", priority: "P2", note: "" },
      { title: "Lost on rural backroads while driving", status: "partial", priority: "P2", note: "" },
    ],
  },
  {
    name: "Evacuation",
    topics: [
      { title: "Go-bag / bug-out bag contents", status: "verified", priority: "P1", note: "FEMA + Ready.gov" },
      { title: "Evacuation zones and shelter locations", status: "verified", priority: "P1", note: "FEMA + American Red Cross" },
      { title: "Evacuation routes: avoiding gridlock", status: "partial", priority: "P2", note: "" },
      { title: "Evacuation order vs. shelter order (decision)", status: "verified", priority: "P1", note: "FEMA + OSHA" },
      { title: "Offline route downloads (primary/alternate)", status: "partial", priority: "P2", note: "" },
      { title: "Household drill schedule and results", status: "partial", priority: "P3", note: "" },
      { title: "Family reunification if separated", status: "verified", priority: "P1", note: "Ready.gov/FEMA" },
      { title: "Immediate/neighborhood/regional meeting places", status: "partial", priority: "P2", note: "" },
      { title: "Vehicle evacuation kit", status: "partial", priority: "P2", note: "" },
      { title: "Pet/livestock evacuation", status: "verified", priority: "P1", note: "ASPCA + AVMA" },
      { title: "Evacuating with medical equipment/power-dependent needs", status: "verified", priority: "P1", note: "American Red Cross + Ready.gov/FEMA" },
      { title: "Public-place evacuation scenarios (work/school/mall)", status: "verified", priority: "P1", note: "OSHA + NFPA 101" },
    ],
  },
  {
    name: "Security & Safety",
    topics: [
      { title: "Active shooter / active attacker response", status: "verified", priority: "P0", note: "CISA Run-Hide-Fight" },
      { title: "Civil unrest, riot, violent demonstration nearby", status: "verified", priority: "P1", note: "ACLU protest safety guidance" },
      { title: "Curfew and checkpoint legal guidance by jurisdiction", status: "verified", priority: "P2", note: "Stop, stay calm, comply" },
      { title: "Suspicious package or explosion threat", status: "verified", priority: "P1", note: "DHS/Ready.gov" },
      { title: "Home intrusion / break-in response", status: "verified", priority: "P1", note: "National Crime Prevention Council" },
      { title: "Situational awareness basics", status: "verified", priority: "P2", note: "DHS See Something Say Something" },
      { title: "Non-escalatory de-escalation techniques", status: "partial", priority: "P2", note: "" },
      { title: "Aggressive/road-rage driver encounter", status: "verified", priority: "P1", note: "State police agencies" },
      { title: "Suspect you're being followed (in a vehicle)", status: "verified", priority: "P1", note: "UCLA PD + Fremont PD" },
      { title: "Parking lot / walking to your car alone at night", status: "verified", priority: "P2", note: "UCLA PD + Fremont PD" },
      { title: "Hostage situation", status: "partial", priority: "P1", note: "No direct federal civilian source found" },
      { title: "Lawful self-defense boundaries (varies by state)", status: "verified", priority: "P2", note: "NCSL — framework only" },
      { title: "Safe-room / panic-room concept", status: "partial", priority: "P2", note: "Simplified to tornado safe-room" },
      { title: "Neighborhood/community mutual-aid security", status: "partial", priority: "P3", note: "" },
      { title: "Weapon storage safety around children", status: "verified", priority: "P2", note: "American Academy of Pediatrics" },
      { title: "Perimeter alarm and tripwire systems", status: "verified", priority: "P2", note: "US Army FM 3-21.8" },
      { title: "Property fortification and access denial", status: "verified", priority: "P2", note: "FEMA 426 + National Crime Prevention Council" },
      { title: "Reducing glint and visual signature", status: "partial", priority: "P3", note: "" },
    ],
  },
  {
    name: "Tools & Repairs",
    topics: [
      { title: "Basic knots for emergencies", status: "verified", priority: "P2", note: "Scouting America" },
      { title: "Improvised repairs (duct tape, tarp, zip-tie fixes)", status: "verified", priority: "P2", note: "US Army FM 4-30.31" },
      { title: "Hand-tool inventory basics", status: "partial", priority: "P3", note: "See Inventory & Supplies" },
      { title: "Boarding up windows (basic carpentry)", status: "verified", priority: "P2", note: "FEMA/Ready.gov" },
      { title: "Rope and cordage strength basics", status: "verified", priority: "P3", note: "Cordage Institute" },
      { title: "Sharpening tools and knives safely", status: "verified", priority: "P3", note: "OSHA/CPSC" },
      { title: "Improvised lever/pry/lift techniques", status: "specialist", priority: "P2", note: "FEMA US&R" },
      { title: "Basic rigging and lifting safety limits", status: "specialist", priority: "P2", note: "OSHA 1910.184 + ASME B30" },
      { title: "Emergency glass cutting and improvised glazing", status: "verified", priority: "P2", note: "Traditional Glazing Standards + DOI" },
      { title: "Z-drag rescue rig (3:1 mechanical advantage)", status: "partial", priority: "P2", note: "" },
      { title: "Hand tool maintenance and rust prevention off-grid", status: "partial", priority: "P2", note: "" },
      { title: "Small engine pull-cord and fuel line replacement", status: "partial", priority: "P3", note: "" },
    ],
  },
  {
    name: "Fishing / Trapping / Food Acquisition",
    topics: [
      { title: "Emergency fishing (handline, improvised gear)", status: "partial", priority: "P2", note: "" },
      { title: "Legal/regulatory boundaries on foraging and trapping", status: "verified", priority: "P2", note: "WDFW + 36 CFR 13.480 — framework only" },
      { title: "Basic snares and deadfalls", status: "partial", priority: "P2", note: "Historical field method, not government-sourced" },
      { title: "Field-dressing and safe handling of wild game", status: "verified", priority: "P1", note: "State wildlife agencies + Extension" },
      { title: "Fish cleaning and safe handling", status: "partial", priority: "P1", note: "Standard technique, not government-sourced" },
      { title: "Identifying unsafe/contaminated fishing waters", status: "verified", priority: "P0", note: "EPA" },
      { title: "Emergency fish traps and baskets", status: "verified", priority: "P2", note: "US Army FM 21-76" },
    ],
  },
  {
    name: "Off-Grid Food Production",
    topics: [
      { title: "Off-grid seed saving and viability testing", status: "verified", priority: "P3", note: "USDA + Organic Seed Alliance" },
      { title: "Emergency grain grinding and flour alternatives", status: "verified", priority: "P2", note: "Penn State Extension + FAO" },
      { title: "Root cellaring and underground cold storage", status: "verified", priority: "P2", note: "University of Wisconsin Extension + USDA" },
      { title: "Off-grid refrigeration and cooler management", status: "verified", priority: "P2", note: "USDA FSIS + CDC" },
      { title: "Solar cooking and solar box oven basics", status: "verified", priority: "P2", note: "Solar Cookers International + FAO" },
      { title: "Emergency food preservation: sun drying and jerky curing", status: "verified", priority: "P2", note: "USDA FSIS + NCHFP" },
      { title: "Pest exclusion for stored grain and seed", status: "verified", priority: "P2", note: "Utah State Extension + Penn State Extension" },
      { title: "Long-term food storage defense (pests, mylar, oxygen absorbers)", status: "verified", priority: "P2", note: "Utah State Extension + USDA NIFA" },
      { title: "Corn nixtamalization (hominy and masa from wood ash)", status: "verified", priority: "P3", note: "FAO" },
      { title: "Emergency pit-smoking and meat preservation", status: "verified", priority: "P2", note: "USDA FSIS + US Forest Service" },
      { title: "Off-grid meat curing (dry salt and brine preservation)", status: "verified", priority: "P2", note: "USDA FSIS + UGA NCHFP" },
      { title: "Emergency grain fermentation (lactic acid preservation and silage)", status: "verified", priority: "P3", note: "FAO + USDA ARS" },
      { title: "Pemmican (traditional long-term meat and fat preservation)", status: "verified", priority: "P3", note: "USDA Historical Food Technology Bulletins" },
      { title: "Meat smoking: hot smoking vs. cold smoking safety", status: "partial", priority: "P2", note: "" },
      { title: "Testing stored grains for dangerous mold (mycotoxins)", status: "partial", priority: "P2", note: "" },
      { title: "Zeer pot: off-grid evaporative cooling", status: "partial", priority: "P3", note: "" },
      { title: "Preserving eggs without refrigeration (water-glassing)", status: "partial", priority: "P3", note: "" },
    ],
  },
  {
    name: "Off-Grid Water Systems",
    topics: [
      { title: "Gravity-fed water filtration systems (drip-bucket construction)", status: "verified", priority: "P2", note: "CDC + WHO" },
      { title: "Field water distillation (solar still evaporation trench)", status: "verified", priority: "P2", note: "US Army FM 21-76" },
      { title: "Well-water pump manual operation (deep and shallow wells)", status: "verified", priority: "P2", note: "EPA + Water Systems Council" },
      { title: "Charcoal/sand bio-sand water filters (slow-sand column)", status: "verified", priority: "P2", note: "WHO + CAWST" },
      { title: "Emergency spring tapping and seep development", status: "verified", priority: "P2", note: "EPA + Peace Corps" },
      { title: "Emergency water well disinfection (shock chlorination)", status: "verified", priority: "P2", note: "EPA + CDC" },
      { title: "Manual hand-drilling for shallow water (sludge and auger methods)", status: "verified", priority: "P3", note: "Peace Corps + UNICEF" },
      { title: "Manual well rehabilitation (surging and air-jetting a clogged well)", status: "verified", priority: "P2", note: "National Ground Water Association + FAO" },
      { title: "Hydraulic ram pump construction from hardware-store pipe fittings", status: "verified", priority: "P3", note: "Practical Action" },
      { title: "Gravity-fed water distribution and pipe sizing", status: "verified", priority: "P2", note: "Peace Corps + IAPMO" },
      { title: "Gravity-fed water filter maintenance and the freeze-fracture risk", status: "partial", priority: "P2", note: "" },
    ],
  },
  {
    name: "Primitive Fire, Fuel & Shelter",
    topics: [
      { title: "Carbon-monoxide safe tent and snow-cave heating", status: "partial", priority: "P1", note: "" },
      { title: "Emergency snow cave construction", status: "partial", priority: "P2", note: "" },
      { title: "Emergency firewood selection and safe burning", status: "verified", priority: "P2", note: "EPA Burnwise + CSIA" },
      { title: "Charcoal production and firebed management", status: "verified", priority: "P3", note: "FAO Forestry + US Forest Service" },
      { title: "Rocket stoves and biochar basics", status: "verified", priority: "P3", note: "Aprovecho Research Center + International Biochar Initiative" },
      { title: "Thatch and shingle primitive roofing", status: "verified", priority: "P3", note: "Peace Corps" },
      { title: "Wilderness thermal reflector shelters", status: "verified", priority: "P2", note: "US Army FM 21-76" },
      { title: "Emergency charcoal gasification (wood gas for engines)", status: "verified", priority: "P3", note: "FEMA + National Academy of Sciences" },
      { title: "Off-grid masonry heater construction (thermal mass heating)", status: "verified", priority: "P2", note: "Masonry Heater Association of North America" },
    ],
  },
  {
    name: "Primitive Crafts & Construction",
    topics: [
      { title: "Emergency blacksmithing and tool forging", status: "verified", priority: "P3", note: "US Army TM 9-237" },
      { title: "Emergency lime and quicklime production", status: "verified", priority: "P3", note: "Practical Action + National Lime Association" },
      { title: "Field brick and adobe making", status: "verified", priority: "P3", note: "Peace Corps + NM Building Code" },
      { title: "Emergency wood ash lye (potash) extraction", status: "verified", priority: "P3", note: "Pioneer chemical manuals + Extension bulletins" },
      { title: "Primitive archery and simple bow fabrication", status: "verified", priority: "P3", note: "Society of Primitive Technology" },
      { title: "Improvised cordage (plant fibers and reverse-wrap)", status: "verified", priority: "P3", note: "US Army FM 21-76" },
      { title: "Emergency bone and horn toolmaking", status: "verified", priority: "P3", note: "Society of Primitive Technology" },
      { title: "Primitive timber joinery (mortise, tenon, and lap joints)", status: "verified", priority: "P3", note: "US Forest Service + Peace Corps" },
      { title: "Emergency mud stucco and wattle-and-daub construction", status: "verified", priority: "P3", note: "Practical Action" },
      { title: "Emergency hide glue and natural resins", status: "verified", priority: "P3", note: "Society of Primitive Technology" },
      { title: "Emergency hide tanning and rawhide production", status: "verified", priority: "P3", note: "Society of Primitive Technology + DOI" },
      { title: "Natural mortar and cob wall construction", status: "verified", priority: "P3", note: "ICC Appendix U + Peace Corps" },
      { title: "Field pottery and clay vessel production (water storage and cooking)", status: "verified", priority: "P3", note: "Primitive Technology Papers + Smithsonian" },
      { title: "Emergency field soap fabrication (cold-process lard soap)", status: "verified", priority: "P3", note: "University Extension + Practical Action" },
      { title: "Field case-hardening of mild steel (pack carburizing)", status: "verified", priority: "P3", note: "ASM International" },
    ],
  },
  {
    name: "Plants — Basic Emergency Reference",
    note: "Deliberately minimal — the full medicinal-plant archive lives in a separate project and stays there.",
    topics: [
      { title: "Most dangerous look-alike poisonous plants", status: "verified", priority: "P0", note: "Poison Control" },
      { title: "Universal edibility test, with real limitations stated plainly", status: "partial", priority: "P1", note: "Deliberately kept low-confidence — framed as a caution about a flawed popular method, not an endorsement" },
      { title: "Plants never to touch or burn", status: "verified", priority: "P0", note: "CDC/NIOSH" },
      { title: "Poison ivy, oak, and sumac: skin contact and rash", status: "verified", priority: "P2", note: "CDC + American Academy of Dermatology" },
      { title: "Getting water from vegetation (solar still method)", status: "verified", priority: "P2", note: "US Army FM 21-76 + Ready.gov" },
      { title: "Dandelion: a common, safe wild edible", status: "verified", priority: "P3", note: "USDA + university extension services" },
      { title: "Clover: a common, safe wild edible", status: "verified", priority: "P3", note: "USDA + university extension services" },
      { title: "Broadleaf plantain: a common, safe wild edible", status: "verified", priority: "P3", note: "USDA + university extension services" },
      { title: "Basic tree ID for firewood/tinder only", status: "new", priority: "P3", note: "Non-medicinal" },
    ],
  },
  {
    name: "Sanitation & Hygiene",
    topics: [
      { title: "Handwashing with scarce water", status: "verified", priority: "P1", note: "USDA + CDC" },
      { title: "Temporary toilet / twin-bucket system", status: "verified", priority: "P1", note: "Twin-Bucket Emergency Toilet system + FEMA/Red Cross" },
      { title: "Diaper, menstrual, incontinence waste", status: "verified", priority: "P1", note: "CDC" },
      { title: "Latrine siting", status: "partial", priority: "P1", note: "CDC WASH" },
      { title: "Emergency biohazard spill cleanup (blood and body fluids)", status: "partial", priority: "P2", note: "" },
      { title: "Chlorine gas from mixing bleach with other cleaners", status: "partial", priority: "P1", note: "" },
      { title: "Greywater disposal", status: "partial", priority: "P1", note: "EPA + state rules vary" },
      { title: "Diarrhea isolation and oral rehydration", status: "specialist", priority: "P0", note: "WHO + CDC" },
      { title: "General emergency sanitation without running water", status: "verified", priority: "P1", note: "CDC + WHO" },
      { title: "Mold and wet-building cleanup", status: "verified", priority: "P1", note: "EPA + CDC" },
      { title: "Long-term waste, pests, vector control", status: "partial", priority: "P2", note: "" },
      { title: "Off-grid hygiene and field sanitation", status: "verified", priority: "P2", note: "WHO + Sphere Handbook" },
      { title: "Disposal of medical waste and soiled dressings", status: "partial", priority: "P2", note: "" },
      { title: "Field laundry: eradicating lice, mites, and bedbugs", status: "partial", priority: "P2", note: "" },
      { title: "Field handwashing stations: the tippy-tap build", status: "partial", priority: "P2", note: "" },
    ],
  },
  {
    name: "Family & Caregiving",
    topics: [
      { title: "Disability, mobility, sensory, caregiver needs", status: "verified", priority: "P1", note: "Red Cross + Ready.gov" },
      { title: "Power-dependent medical equipment failure plan", status: "verified", priority: "P0", note: "HHS emPOWER Program + American Red Cross" },
      { title: "Children in emergencies (age-appropriate prep)", status: "partial", priority: "P2", note: "" },
      { title: "Elderly-specific emergency needs", status: "verified", priority: "P2", note: "CDC + Administration for Community Living" },
      { title: "Pregnancy considerations across scenarios", status: "verified", priority: "P1", note: "ACOG + CDC" },
      { title: "Psychological first aid and grief support", status: "verified", priority: "P2", note: "SAMHSA + Disaster Distress Helpline" },
      { title: "Helping children cope with disaster stress", status: "verified", priority: "P2", note: "CDC + American Red Cross" },
      { title: "Family plan: getting one onto every phone", status: "verified", priority: "P2", note: "Built: Family Plan screen, shared by file, medical opt-in per person" },
      { title: "Medication continuity plan for dependents", status: "partial", priority: "P2", note: "" },
      { title: "Improvised feminine hygiene pads", status: "partial", priority: "P2", note: "" },
    ],
  },
  {
    name: "Inventory & Supplies",
    note: "The Supply Inventory screen counts these and works out how long they last.",
    topics: [
      { title: "Food inventory (item/qty/calories/expiration/location)", status: "verified", priority: "P2", note: "Built: Supply Inventory. Calories per unit from USDA FoodData Central" },
      { title: "Water inventory and treatment supplies", status: "verified", priority: "P0", note: "CDC + FEMA" },
      { title: "Medical/prescription/OTC inventory and expirations", status: "verified", priority: "P0", note: "FDA + AMA" },
      { title: "Power inventory (batteries/banks/solar/fuel)", status: "verified", priority: "P1", note: "Built: Supply Inventory, with a power-bank charge estimate" },
      { title: "Tools and repair-supply inventory", status: "verified", priority: "P2", note: "Built: Supply Inventory" },
      { title: "Pet-supply inventory", status: "verified", priority: "P2", note: "Built: Supply Inventory" },
      { title: "Hygiene-supply inventory", status: "verified", priority: "P2", note: "Built: Supply Inventory" },
      { title: "Emergency-document inventory", status: "verified", priority: "P2", note: "Ready.gov EFFAK + NIST" },
      { title: "Fuel inventory", status: "verified", priority: "P1", note: "NFPA 30 + Small Engine Manufacturers Association" },
      { title: "Ammunition and propellant storage safety", status: "verified", priority: "P2", note: "NFPA 495 + SAAMI" },
      { title: "Calculated days-of-water/food remaining", status: "verified", priority: "P2", note: "Built: Supply Inventory. 1 gal/person/day per Ready.gov" },
      { title: "Expiring-soon and missing-supplies alerts", status: "verified", priority: "P2", note: "Built: Supply Inventory" },
      { title: "Maintaining firearms in dusty or freezing conditions", status: "partial", priority: "P3", note: "" },
      { title: "Establishing barter inventory tracking without electronics", status: "partial", priority: "P3", note: "" },
    ],
  },
  {
    name: "Preparedness Plans",
    note: "Meant to become checklists generated from the underlying content.",
    topics: [
      { title: "Home fire escape plan", status: "verified", priority: "P1", note: "NFPA" },
      { title: "Tornado plan", status: "verified", priority: "P1", note: "NOAA/NWS + FEMA" },
      { title: "Hurricane plan", status: "verified", priority: "P1", note: "Ready.gov/FEMA + American Red Cross" },
      { title: "Flood evacuation plan", status: "verified", priority: "P1", note: "FEMA + Ready.gov" },
      { title: "Wildfire evacuation plan", status: "verified", priority: "P1", note: "NFPA Firewise USA + Ready.gov/CAL FIRE" },
      { title: "Power outage plan", status: "partial", priority: "P2", note: "" },
      { title: "Winter storm plan", status: "verified", priority: "P1", note: "CDC + Ready.gov" },
      { title: "Medical emergency plan (household-specific)", status: "verified", priority: "P1", note: "AHA + American Red Cross" },
      { title: "Pet evacuation plan", status: "partial", priority: "P2", note: "" },
      { title: "Family separation / reunification plan", status: "verified", priority: "P1", note: "Ready.gov/FEMA + AAP" },
      { title: "Bug-out / evacuation plan (general)", status: "verified", priority: "P1", note: "Ready.gov/FEMA + American Red Cross" },
      { title: "Shelter-in-place plan", status: "verified", priority: "P1", note: "CDC + FEMA" },
      { title: "Grid-down barter mechanics and resource staging", status: "verified", priority: "P3", note: "Red Cross + DoD Civil Affairs" },
      { title: "Documenting storm and disaster damage for insurance and legal claims", status: "partial", priority: "P3", note: "" },
      { title: "Home emergency supplies (72 hours to 2 weeks)", status: "partial", priority: "P2", note: "" },
    ],
  },
  {
    name: "Reference Library",
    topics: [
      { title: "Longer-form recovery manuals", status: "partial", priority: "P2", note: "Flood/wildfire reentry, utility restoration" },
      { title: "Foundational source bibliography", status: "verified", priority: "P3", note: "" },
      { title: "Research and Evidence Standard (the rulebook)", status: "verified", priority: "P3", note: "" },
      { title: "Claim Verification Ledger and Publication Gate", status: "verified", priority: "P3", note: "" },
      { title: "Master Scenario Coverage Tracker (historical snapshot)", status: "verified", priority: "P3", note: "" },
      { title: "App engineering readiness checklist", status: "pending", priority: "P2", note: "" },
      { title: "Military/field-manual-derived survival-kit lessons", status: "partial", priority: "P3", note: "" },
      { title: "Community after-action lessons from real outages/storms", status: "partial", priority: "P3", note: "" },
    ],
  },
];
