// Master Content Map, ported from the planning artifact.
// status: how well-sourced the guidance is. priority: how time-critical it is.
export type ArticleStatus = "verified" | "specialist" | "partial" | "pending" | "new";
export type Priority = "P0" | "P1" | "P2" | "P3";

export interface Topic {
  title: string;
  status: ArticleStatus;
  priority: Priority;
  note: string;
}

export interface Category {
  name: string;
  note?: string;
  topics: Topic[];
}

export const CATEGORIES: Category[] = [
  {
    name: "What To Do In An Emergency",
    note: "Quick numbered-step versions of the full articles below.",
    topics: [
      { title: "Severe bleeding (tourniquet)", status: "specialist", priority: "P0", note: "Full article drafted" },
      { title: "Not breathing / cardiac arrest (CPR/AED)", status: "specialist", priority: "P0", note: "Full article drafted" },
      { title: "Choking", status: "specialist", priority: "P0", note: "2025 guidance drafted" },
      { title: "Unconscious, breathing, cause unknown", status: "pending", priority: "P0", note: "No dedicated card yet" },
      { title: "Poisoning (swallowed/inhaled/skin/eye)", status: "verified", priority: "P0", note: "" },
      { title: "Burn (thermal/chemical)", status: "specialist", priority: "P0", note: "" },
      { title: "Severe allergic reaction / epinephrine", status: "specialist", priority: "P0", note: "" },
      { title: "Heart-attack symptoms / aspirin boundary", status: "specialist", priority: "P0", note: "" },
      { title: "Stroke symptoms", status: "specialist", priority: "P0", note: "" },
      { title: "Broken bone / fracture", status: "specialist", priority: "P0", note: "Full article drafted" },
      { title: "Hypothermia", status: "verified", priority: "P0", note: "" },
      { title: "Heat illness (exhaustion/stroke)", status: "verified", priority: "P0", note: "" },
      { title: "Animal emergency (poisoning)", status: "specialist", priority: "P0", note: "" },
      { title: "Emergency childbirth", status: "pending", priority: "P0", note: "Full article still pending" },
      { title: "Seizure", status: "specialist", priority: "P0", note: "" },
      { title: "Drowning / near-drowning rescue", status: "new", priority: "P0", note: "No article yet" },
      { title: "Active violence (run-hide-fight quick card)", status: "new", priority: "P1", note: "See Security & Safety" },
      { title: "Structure fire — get out now", status: "verified", priority: "P0", note: "" },
    ],
  },
  {
    name: "Medical & First Aid",
    topics: [
      { title: "Scene safety and triage order", status: "specialist", priority: "P0", note: "" },
      { title: "Adult CPR/AED", status: "specialist", priority: "P0", note: "" },
      { title: "Pediatric/infant CPR and choking", status: "specialist", priority: "P0", note: "2025 AHA/AAP guidelines" },
      { title: "Adult choking, 2025 sequence", status: "specialist", priority: "P0", note: "" },
      { title: "Severe bleeding and tourniquet", status: "specialist", priority: "P0", note: "" },
      { title: "Junctional bleeding and wound packing", status: "specialist", priority: "P0", note: "TCCC/CoTCCC military standard" },
      { title: "Wound irrigation and when not to close", status: "specialist", priority: "P0", note: "" },
      { title: "Thermal burns", status: "specialist", priority: "P0", note: "" },
      { title: "Chemical and electrical burns", status: "partial", priority: "P0", note: "Chemical drafted; electrical not yet" },
      { title: "Fractures, splints, circulation checks", status: "specialist", priority: "P0", note: "American Red Cross" },
      { title: "Head, neck and spinal injury", status: "specialist", priority: "P0", note: "American Red Cross" },
      { title: "Chest and abdominal trauma (open chest wound)", status: "specialist", priority: "P0", note: "" },
      { title: "Shock and hypothermia prevention (medical)", status: "partial", priority: "P0", note: "" },
      { title: "Emergency childbirth and newborn care", status: "specialist", priority: "P0", note: "Red Cross + AAP/ACOG" },
      { title: "Severe allergic reaction / epinephrine", status: "specialist", priority: "P0", note: "" },
      { title: "Anaphylaxis when no epinephrine is available", status: "verified", priority: "P0", note: "ASCIA + AAAAI/ACAAI" },
      { title: "Mild allergic reaction or hives without antihistamine", status: "verified", priority: "P2", note: "ACAAI + AAD" },
      { title: "Asthma, COPD, breathing distress", status: "specialist", priority: "P0", note: "2024 AHA/Red Cross" },
      { title: "Diabetes, insulin interruption, hypoglycemia", status: "specialist", priority: "P0", note: "" },
      { title: "Seizure", status: "specialist", priority: "P0", note: "" },
      { title: "Stroke", status: "specialist", priority: "P0", note: "" },
      { title: "Heart attack and aspirin boundaries", status: "specialist", priority: "P0", note: "" },
      { title: "Dehydration and oral rehydration", status: "partial", priority: "P1", note: "" },
      { title: "Fever, respiratory infection, isolation", status: "specialist", priority: "P1", note: "" },
      { title: "Sepsis warning signs", status: "specialist", priority: "P1", note: "CDC + Sepsis Alliance + ACEP" },
      { title: "Dental pain, broken tooth, facial swelling", status: "verified", priority: "P1", note: "ADA/MouthHealthy + JADA" },
      { title: "Eye injury and chemical irrigation", status: "verified", priority: "P0", note: "AAO + Mayo Clinic" },
      { title: "Smoke inhalation and carbon monoxide", status: "specialist", priority: "P0", note: "CDC" },
      { title: "Snakebite and venomous arthropods (human)", status: "specialist", priority: "P0", note: "CDC/Red Cross/Mayo" },
      { title: "Tick bite, rabies exposure, animal bite (human)", status: "specialist", priority: "P1", note: "CDC rabies PEP guidance" },
      { title: "Dog/animal bite wound care and infection risk", status: "verified", priority: "P1", note: "CDC" },
      { title: "Ankle sprain / twisted ankle", status: "verified", priority: "P3", note: "Mayo Clinic + AAOS" },
      { title: "Unknown swallowed poison, no induced vomiting", status: "verified", priority: "P0", note: "" },
      { title: "Poison exposure by eye, skin, inhalation", status: "verified", priority: "P0", note: "" },
      { title: "Activated-charcoal limitations (human)", status: "verified", priority: "P0", note: "" },
      { title: "Opioid overdose and naloxone", status: "specialist", priority: "P0", note: "" },
      { title: "Non-opioid medication overdose", status: "verified", priority: "P0", note: "Poison Control 1-800-222-1222" },
      { title: "Wild plant/mushroom poisoning (human)", status: "verified", priority: "P0", note: "Poison Control + CA Poison Control" },
      { title: "Pesticide exposure", status: "specialist", priority: "P1", note: "EPA" },
      { title: "Medication storage, expiration, continuity", status: "verified", priority: "P1", note: "" },
      { title: "Poison-record log (substance/amount/time/symptoms)", status: "partial", priority: "P2", note: "" },
    ],
  },
  {
    name: "Disasters",
    topics: [
      { title: "Tornado warning shelter", status: "verified", priority: "P1", note: "" },
      { title: "Hurricane watch/warning/evacuation", status: "partial", priority: "P1", note: "" },
      { title: "Storm surge evacuation", status: "partial", priority: "P1", note: "" },
      { title: "River / prolonged inland flood", status: "pending", priority: "P1", note: "Not yet drafted" },
      { title: "Flash flood", status: "verified", priority: "P0", note: "" },
      { title: "Driving into flood water (Turn Around, Don't Drown)", status: "verified", priority: "P0", note: "NWS + FEMA + CDC" },
      { title: "Severe thunderstorm, straight-line wind, hail", status: "verified", priority: "P1", note: "NWS" },
      { title: "Lightning", status: "verified", priority: "P0", note: "" },
      { title: "Winter storm, blizzard, ice storm", status: "verified", priority: "P1", note: "CDC + Ready.gov" },
      { title: "Extreme heat illness", status: "verified", priority: "P0", note: "" },
      { title: "Wildfire warning, evacuation, smoke", status: "partial", priority: "P1", note: "" },
      { title: "Earthquake shaking and aftershocks", status: "verified", priority: "P1", note: "" },
      { title: "Landslide and mudflow", status: "verified", priority: "P1", note: "USGS + CDC" },
      { title: "Dam or levee failure", status: "partial", priority: "P1", note: "FEMA" },
      { title: "Tsunami", status: "verified", priority: "P0", note: "NOAA/NWS" },
      { title: "Drought and prolonged water shortage", status: "partial", priority: "P2", note: "NOAA NIDIS + USGS" },
      { title: "Volcanic ash", status: "verified", priority: "P2", note: "USGS Volcano Hazards Program" },
      { title: "Natural-gas or propane odor", status: "verified", priority: "P0", note: "" },
      { title: "Carbon-monoxide alarm or symptoms (general)", status: "verified", priority: "P0", note: "NFPA" },
      { title: "Chemical plume: evacuate or shelter", status: "verified", priority: "P0", note: "" },
      { title: "Unknown industrial smoke or fire", status: "verified", priority: "P0", note: "PHMSA/Mass.gov" },
      { title: "Train/truck hazardous-material release", status: "verified", priority: "P0", note: "PHMSA Emergency Response Guidebook" },
      { title: "Nuclear detonation flash/blast/fallout", status: "verified", priority: "P0", note: "CDC" },
      { title: "Dirty bomb vs. nuclear explosion distinction", status: "verified", priority: "P0", note: "CDC" },
      { title: "Radiation shelter and decontamination", status: "verified", priority: "P0", note: "CDC" },
      { title: "Biological outbreak and household isolation", status: "pending", priority: "P0", note: "Not yet drafted" },
      { title: "Aircraft impact/explosion in a building", status: "new", priority: "P1", note: "Outline only" },
    ],
  },
  {
    name: "Water",
    topics: [
      { title: "Emergency stored-water quantity and containers", status: "verified", priority: "P0", note: "" },
      { title: "Tap water suspected unsafe", status: "verified", priority: "P0", note: "" },
      { title: "Boiling for microbial hazards", status: "verified", priority: "P0", note: "" },
      { title: "Concentration-aware household bleach treatment", status: "verified", priority: "P0", note: "" },
      { title: "Portable filter limits", status: "verified", priority: "P0", note: "" },
      { title: "Emergency household water sources", status: "verified", priority: "P1", note: "" },
      { title: "Flooded private well, initial response", status: "verified", priority: "P0", note: "" },
      { title: "Hot-water tank safe isolation and draining", status: "pending", priority: "P1", note: "Not yet drafted" },
      { title: "Household pipe gravity draining", status: "pending", priority: "P2", note: "Not yet drafted" },
      { title: "Rainwater collection and first-flush contamination", status: "partial", priority: "P1", note: "" },
      { title: "Saltwater/brackish desalination limits", status: "partial", priority: "P2", note: "" },
      { title: "Chemical/fuel/algal-toxin/radiological rejection", status: "partial", priority: "P0", note: "" },
      { title: "UV purification methods (e.g. SODIS, UV pens)", status: "new", priority: "P1", note: "Not yet researched" },
    ],
  },
  {
    name: "Food",
    topics: [
      { title: "Refrigerator/freezer outage timing", status: "verified", priority: "P1", note: "CDC + FoodSafety.gov" },
      { title: "Flood-contaminated food and container salvage", status: "verified", priority: "P0", note: "USDA/FSIS" },
      { title: "Damaged/bulging/rusted cans", status: "verified", priority: "P0", note: "USDA/FSIS" },
      { title: "Manual can opening and injury control", status: "partial", priority: "P2", note: "Commonsense practical safety only" },
      { title: "Outdoor stove, grill, and fire cooking", status: "verified", priority: "P1", note: "CPSC/NFPA" },
      { title: "Safe cooking temperatures", status: "verified", priority: "P1", note: "FoodSafety.gov" },
      { title: "Cross-contamination without running water", status: "verified", priority: "P1", note: "CDC/FSIS" },
      { title: "Infant feeding without safe water or refrigeration", status: "verified", priority: "P0", note: "CDC" },
      { title: "Dry staples, rationing, special diets", status: "verified", priority: "P2", note: "Ready.gov/FEMA + UGA Extension" },
      { title: "Thawing, refreezing, ice-crystal rule", status: "verified", priority: "P1", note: "CDC/FoodSafety.gov" },
      { title: "Dry ice ventilation and handling", status: "verified", priority: "P1", note: "Cornell EHS + NIH ORS" },
      { title: "Retained-heat cooking, low-fuel", status: "partial", priority: "P1", note: "Haybox technique" },
      { title: "Food dehydration and humidity limits", status: "partial", priority: "P2", note: "" },
      { title: "Water-bath vs. pressure canning", status: "verified", priority: "P0", note: "CDC + NCHFP" },
      { title: "Botulism warning signs and disposal", status: "verified", priority: "P0", note: "CDC" },
      { title: "Rodent/insect contamination", status: "verified", priority: "P1", note: "FDA" },
      { title: "Wild game handling and cooking", status: "pending", priority: "P1", note: "See Fishing/Trapping/Food Acquisition" },
      { title: "Fish toxins and harmful algal blooms", status: "pending", priority: "P0", note: "See Fishing/Trapping/Food Acquisition" },
      { title: "Food rotation / FIFO principles", status: "new", priority: "P3", note: "See Inventory & Supplies" },
    ],
  },
  {
    name: "Shelter & Heat",
    topics: [
      { title: "Tornado warning shelter", status: "verified", priority: "P1", note: "" },
      { title: "Lightning shelter", status: "verified", priority: "P0", note: "" },
      { title: "Heat exhaustion and heat stroke", status: "verified", priority: "P0", note: "" },
      { title: "Wildfire smoke clean room", status: "partial", priority: "P1", note: "" },
      { title: "Structure fire escape", status: "verified", priority: "P0", note: "" },
      { title: "Gas or propane odor", status: "verified", priority: "P0", note: "" },
      { title: "Carbon-monoxide alarm or symptoms", status: "pending", priority: "P0", note: "Explicit tracker gap" },
      { title: "Winter outage and safe-room selection", status: "verified", priority: "P1", note: "" },
      { title: "Hypothermia recognition and first aid", status: "verified", priority: "P0", note: "" },
      { title: "Frostbite and refreezing risk", status: "verified", priority: "P0", note: "" },
      { title: "Extreme-heat home cooling without power", status: "verified", priority: "P0", note: "" },
      { title: "Safe indoor lighting during blackout", status: "verified", priority: "P1", note: "" },
      { title: "Fireplace/chimney limitations before use", status: "verified", priority: "P0", note: "" },
      { title: "Wood-stove and combustion-heater safety", status: "verified", priority: "P0", note: "" },
      { title: "Outdoor cooking placement and fire control", status: "verified", priority: "P1", note: "" },
      { title: "Campfire site and extinguishment", status: "verified", priority: "P1", note: "" },
      { title: "Wildland fire ignition restrictions", status: "pending", priority: "P1", note: "Not yet drafted" },
      { title: "Temporary shelter and ventilation", status: "pending", priority: "P1", note: "Not yet drafted" },
      { title: "Damaged roof, windows, weatherproofing", status: "pending", priority: "P2", note: "Not yet drafted" },
      { title: "Fire without a lighter (ferro rod, steel wool, friction)", status: "pending", priority: "P2", note: "Withheld pending field-safety review" },
      { title: "Improvised skillet-support / cook-fire rig", status: "pending", priority: "P2", note: "Withheld pending stability/burn-hazard validation" },
    ],
  },
  {
    name: "Power & Lighting",
    topics: [
      { title: "General power outage", status: "verified", priority: "P1", note: "American Red Cross + CDC" },
      { title: "Generator carbon-monoxide safety", status: "verified", priority: "P0", note: "" },
      { title: "Generator electrical connection / backfeed prevention", status: "verified", priority: "P0", note: "Safe Electricity + NEC" },
      { title: "Downed power lines and electrified water", status: "verified", priority: "P0", note: "ESFI + utility companies" },
      { title: "Appliance reconnection and surge risk", status: "partial", priority: "P1", note: "" },
      { title: "Solar panel, charge controller, power-bank chain", status: "partial", priority: "P2", note: "Morningstar" },
      { title: "Lithium battery heat/cold/fire/storage", status: "verified", priority: "P1", note: "CPSC + NY State DHSES" },
      { title: "Vehicle charging without CO exposure", status: "verified", priority: "P0", note: "NFPA" },
      { title: "Phone low-power settings and battery budgeting", status: "verified", priority: "P2", note: "Ready.gov/FEMA + FCC + DOE" },
      { title: "Suspected EMP: what can/cannot be inferred", status: "verified", priority: "P3", note: "CISA/DHS/FEMA" },
      { title: "Battery watt-hour budgeting (calculator)", status: "new", priority: "P2", note: "" },
    ],
  },
  {
    name: "Home Systems",
    topics: [
      { title: "Water, electricity, gas, propane shutoffs", status: "verified", priority: "P1", note: "Ready.gov/FEMA" },
      { title: "Electrical panel and de-energizing verification", status: "specialist", priority: "P0", note: "Flagged for qualified review" },
      { title: "Broken water pipe isolation and temp patch", status: "partial", priority: "P1", note: "" },
      { title: "Frozen pipe prevention and thawing", status: "partial", priority: "P1", note: "" },
      { title: "Sewage backup", status: "partial", priority: "P1", note: "" },
      { title: "Septic failure", status: "partial", priority: "P1", note: "" },
      { title: "Roof leak and temporary tarp", status: "partial", priority: "P1", note: "" },
      { title: "Structural damage and unsafe-building signs", status: "partial", priority: "P1", note: "" },
      { title: "Well power and pressure system", status: "partial", priority: "P1", note: "" },
      { title: "Sump-pump failure", status: "partial", priority: "P2", note: "RESEARCH HOLD" },
      { title: "Water-heater isolation", status: "partial", priority: "P1", note: "RESEARCH HOLD" },
      { title: "Appliance failure and safe restart", status: "new", priority: "P2", note: "" },
    ],
  },
  {
    name: "Vehicles & Mechanics",
    topics: [
      { title: "Tire change and roadside visibility", status: "partial", priority: "P1", note: "NHTSA stats" },
      { title: "Tire puncture limits and plug boundaries", status: "verified", priority: "P2", note: "NHTSA + Tire Industry Association" },
      { title: "Jump-start sequence by vehicle type", status: "verified", priority: "P1", note: "AAA standard sequence" },
      { title: "Electric/hybrid vehicle crash and flood hazards", status: "partial", priority: "P0", note: "" },
      { title: "Vehicle submersion: escaping a sinking car", status: "verified", priority: "P0", note: "AAA + Kids and Car Safety" },
      { title: "Vehicle overheating", status: "partial", priority: "P1", note: "AAA" },
      { title: "Vehicle stranded in heat or cold", status: "verified", priority: "P0", note: "CDC + Ready.gov/FEMA + AAA + AZDOT" },
      { title: "Hit an animal with your car (deer/wildlife strike)", status: "verified", priority: "P2", note: "PennDOT + PA Insurance Dept + Michigan State Police" },
      { title: "Fuel storage, transfer, fire safety", status: "partial", priority: "P0", note: "" },
      { title: "Small-engine troubleshooting", status: "partial", priority: "P2", note: "Generac official troubleshooting guide" },
      { title: "Chainsaw and cutting-tool safety", status: "partial", priority: "P1", note: "" },
      { title: "Manual siphon-pump legal/safety boundaries", status: "verified", priority: "P2", note: "CDC + CPSC" },
      { title: "Immediate steps after a car crash", status: "verified", priority: "P1", note: "US DOT + NHTSA" },
      { title: "Spark-plug inspection/replacement", status: "partial", priority: "P2", note: "Closed by the small-engine troubleshooting research (Generac guide)" },
    ],
  },
  {
    name: "Animals & Pets",
    topics: [
      { title: "Unknown pet poison response", status: "specialist", priority: "P0", note: "" },
      { title: "Dog/cat NSAID and acetaminophen boundaries", status: "specialist", priority: "P0", note: "" },
      { title: "Pet evacuation kit and records", status: "verified", priority: "P2", note: "" },
      { title: "Veterinary activated-charcoal decision boundary", status: "specialist", priority: "P0", note: "" },
      { title: "Milk thistle/silymarin evidence and limits", status: "specialist", priority: "P1", note: "" },
      { title: "Dog xylitol exposure", status: "specialist", priority: "P0", note: "" },
      { title: "Cat true-lily exposure", status: "specialist", priority: "P0", note: "" },
      { title: "Common toxic foods (pets)", status: "specialist", priority: "P0", note: "" },
      { title: "Dog heatstroke", status: "partial", priority: "P0", note: "Cool-first, transport-second" },
      { title: "Cat-specific heatstroke", status: "specialist", priority: "P0", note: "RVC + PDSA — gradual cooling only" },
      { title: "Pet hypothermia and frostbite", status: "specialist", priority: "P0", note: "American Red Cross Pet First Aid" },
      { title: "Pet trauma, bleeding, fractures, safe transport", status: "specialist", priority: "P0", note: "AVMA + Merck Veterinary Manual" },
      { title: "Bloat/GDV warning signs", status: "specialist", priority: "P0", note: "AAHA — no safe home treatment" },
      { title: "Pet seizure and breathing distress", status: "specialist", priority: "P0", note: "AVMA + PDSA" },
      { title: "Pet snakebite and envenomation", status: "verified", priority: "P0", note: "Merck Veterinary Manual + VCA" },
      { title: "Contaminated coat/skin decontamination", status: "partial", priority: "P1", note: "" },
      { title: "Wild animal encounter: bears (black vs. grizzly)", status: "verified", priority: "P1", note: "National Park Service" },
      { title: "Wild animal encounter: mountain lion/cougar", status: "verified", priority: "P1", note: "US Fish & Wildlife Service + NPS" },
      { title: "Wild animal encounter: coyote", status: "verified", priority: "P2", note: "San Diego Humane Society" },
      { title: "Wild animal encounter: alligator", status: "verified", priority: "P1", note: "Florida FWC" },
      { title: "Wild animal encounter: snake (avoidance, not bite treatment)", status: "verified", priority: "P1", note: "CDC/NIOSH + US Army" },
      { title: "Wildlife displaced by disaster (general principle)", status: "verified", priority: "P2", note: "Texas Parks & Wildlife" },
      { title: "Livestock water, feed, evacuation", status: "verified", priority: "P1", note: "USDA FSA" },
      { title: "Downed fences and escaped animals", status: "partial", priority: "P1", note: "MU/OSU Extension" },
      { title: "Carcass handling and zoonotic disease", status: "verified", priority: "P1", note: "CDC + USDA APHIS" },
    ],
  },
  {
    name: "Communication",
    topics: [
      { title: "No cellular service or internet", status: "verified", priority: "P1", note: "FCC/FEMA" },
      { title: "NOAA Weather Radio", status: "verified", priority: "P1", note: "NOAA/NWS" },
      { title: "AM/FM emergency broadcasts", status: "verified", priority: "P1", note: "FEMA IPAWS/EAS" },
      { title: "FRS, GMRS, MURS, CB, amateur-radio boundaries", status: "verified", priority: "P2", note: "47 CFR Part 95/97" },
      { title: "Texting vs. calling during network congestion", status: "partial", priority: "P2", note: "" },
      { title: "Family communication plan and rendezvous points", status: "partial", priority: "P1", note: "" },
      { title: "Paper maps, contacts, critical records backup", status: "partial", priority: "P2", note: "" },
      { title: "Emergency alert verification and rumor control", status: "verified", priority: "P1", note: "FEMA Rumor Response" },
      { title: "Amateur (ham) radio licensing basics", status: "new", priority: "P3", note: "" },
    ],
  },
  {
    name: "Navigation",
    topics: [
      { title: "Reading a paper/topographic map", status: "verified", priority: "P2", note: "FM 3-25.26 (US Army)" },
      { title: "Compass use and orientation", status: "verified", priority: "P2", note: "FM 3-25.26 + MSU Extension" },
      { title: "Land navigation without GPS", status: "verified", priority: "P2", note: "FM 3-25.26" },
      { title: "Downloading and using offline map packs", status: "partial", priority: "P2", note: "App feature" },
      { title: "Identifying safe vs. unsafe routes during a disaster", status: "verified", priority: "P1", note: "Ready.gov/FEMA" },
      { title: "Finding cardinal directions without a compass", status: "verified", priority: "P3", note: "FM 3-25.26 Appendix F" },
      { title: "Marking private landmarks/hazards on offline maps", status: "partial", priority: "P3", note: "" },
    ],
  },
  {
    name: "Evacuation",
    topics: [
      { title: "Go-bag / bug-out bag contents", status: "partial", priority: "P1", note: "" },
      { title: "Evacuation zones and shelter locations", status: "partial", priority: "P1", note: "" },
      { title: "Evacuation order vs. shelter order (decision)", status: "verified", priority: "P1", note: "FEMA + OSHA" },
      { title: "Offline route downloads (primary/alternate)", status: "partial", priority: "P2", note: "" },
      { title: "Household drill schedule and results", status: "new", priority: "P3", note: "" },
      { title: "Family reunification if separated", status: "verified", priority: "P1", note: "Ready.gov/FEMA" },
      { title: "Immediate/neighborhood/regional meeting places", status: "partial", priority: "P2", note: "" },
      { title: "Vehicle evacuation kit", status: "new", priority: "P2", note: "" },
      { title: "Pet/livestock evacuation", status: "partial", priority: "P1", note: "See Animals & Pets" },
      { title: "Evacuating with medical equipment/power-dependent needs", status: "partial", priority: "P1", note: "" },
      { title: "Public-place evacuation scenarios (work/school/mall)", status: "partial", priority: "P1", note: "" },
    ],
  },
  {
    name: "Security & Safety",
    topics: [
      { title: "Active shooter / active attacker response", status: "verified", priority: "P0", note: "CISA Run-Hide-Fight" },
      { title: "Civil unrest, riot, violent demonstration nearby", status: "verified", priority: "P1", note: "ACLU protest safety guidance" },
      { title: "Curfew and checkpoint legal guidance by jurisdiction", status: "verified", priority: "P2", note: "Stop, stay calm, comply" },
      { title: "Suspicious package or explosion threat", status: "verified", priority: "P1", note: "DHS/Ready.gov" },
      { title: "Home intrusion / break-in response", status: "verified", priority: "P1", note: "National Crime Prevention Council" },
      { title: "Situational awareness basics", status: "verified", priority: "P2", note: "DHS See Something Say Something" },
      { title: "Non-escalatory de-escalation techniques", status: "pending", priority: "P2", note: "Explicit tracker gap" },
      { title: "Aggressive/road-rage driver encounter", status: "verified", priority: "P1", note: "State police agencies" },
      { title: "Suspect you're being followed (in a vehicle)", status: "verified", priority: "P1", note: "UCLA PD + Fremont PD" },
      { title: "Parking lot / walking to your car alone at night", status: "verified", priority: "P2", note: "UCLA PD + Fremont PD" },
      { title: "Hostage situation", status: "partial", priority: "P1", note: "No direct federal civilian source found" },
      { title: "Lawful self-defense boundaries (varies by state)", status: "verified", priority: "P2", note: "NCSL — framework only" },
      { title: "Safe-room / panic-room concept", status: "verified", priority: "P2", note: "Simplified to tornado safe-room" },
      { title: "Neighborhood/community mutual-aid security", status: "new", priority: "P3", note: "No authoritative source found" },
      { title: "Weapon storage safety around children", status: "verified", priority: "P2", note: "American Academy of Pediatrics" },
    ],
  },
  {
    name: "Tools & Repairs",
    topics: [
      { title: "Basic knots for emergencies", status: "verified", priority: "P2", note: "Scouting America" },
      { title: "Improvised repairs (duct tape, tarp, zip-tie fixes)", status: "new", priority: "P2", note: "" },
      { title: "Hand-tool inventory basics", status: "new", priority: "P3", note: "See Inventory & Supplies" },
      { title: "Boarding up windows (basic carpentry)", status: "verified", priority: "P2", note: "FEMA/Ready.gov" },
      { title: "Rope and cordage strength basics", status: "verified", priority: "P3", note: "Cordage Institute" },
      { title: "Sharpening tools and knives safely", status: "verified", priority: "P3", note: "OSHA/CPSC" },
      { title: "Improvised lever/pry/lift techniques", status: "new", priority: "P2", note: "" },
    ],
  },
  {
    name: "Fishing / Trapping / Food Acquisition",
    topics: [
      { title: "Emergency fishing (handline, improvised gear)", status: "new", priority: "P2", note: "" },
      { title: "Legal/regulatory boundaries on foraging and trapping", status: "verified", priority: "P2", note: "WDFW + 36 CFR 13.480 — framework only" },
      { title: "Basic snares and deadfalls", status: "partial", priority: "P2", note: "Historical field method, not government-sourced" },
      { title: "Field-dressing and safe handling of wild game", status: "verified", priority: "P1", note: "State wildlife agencies + Extension" },
      { title: "Fish cleaning and safe handling", status: "partial", priority: "P1", note: "Standard technique, not government-sourced" },
      { title: "Identifying unsafe/contaminated fishing waters", status: "verified", priority: "P0", note: "EPA" },
    ],
  },
  {
    name: "Plants — Basic Emergency Reference",
    note: "Deliberately minimal — the full medicinal-plant archive lives in a separate project and stays there.",
    topics: [
      { title: "Most dangerous look-alike poisonous plants", status: "verified", priority: "P0", note: "Poison Control" },
      { title: "Universal edibility test, with real limitations stated plainly", status: "partial", priority: "P1", note: "Deliberately kept low-confidence — framed as a caution about a flawed popular method, not an endorsement" },
      { title: "Plants never to touch or burn", status: "verified", priority: "P0", note: "CDC/NIOSH" },
      { title: "Poison ivy, oak, and sumac: skin contact and rash", status: "verified", priority: "P2", note: "CDC + American Academy of Dermatology" },
      { title: "Getting water from vegetation (solar still method)", status: "verified", priority: "P2", note: "US Army FM 21-76 + Ready.gov" },
      { title: "Dandelion: a common, safe wild edible", status: "verified", priority: "P3", note: "USDA + university extension services" },
      { title: "Clover: a common, safe wild edible", status: "verified", priority: "P3", note: "USDA + university extension services" },
      { title: "Broadleaf plantain: a common, safe wild edible", status: "verified", priority: "P3", note: "USDA + university extension services" },
      { title: "Basic tree ID for firewood/tinder only", status: "new", priority: "P3", note: "Non-medicinal" },
    ],
  },
  {
    name: "Sanitation & Hygiene",
    topics: [
      { title: "Handwashing with scarce water", status: "verified", priority: "P1", note: "USDA + CDC" },
      { title: "Temporary toilet / twin-bucket system", status: "pending", priority: "P1", note: "" },
      { title: "Diaper, menstrual, incontinence waste", status: "verified", priority: "P1", note: "CDC" },
      { title: "Latrine siting", status: "partial", priority: "P1", note: "CDC WASH" },
      { title: "Greywater disposal", status: "partial", priority: "P1", note: "EPA + state rules vary" },
      { title: "Diarrhea isolation and oral rehydration", status: "partial", priority: "P0", note: "See also Medical & First Aid" },
      { title: "General emergency sanitation without running water", status: "partial", priority: "P1", note: "" },
      { title: "Mold and wet-building cleanup", status: "partial", priority: "P1", note: "" },
      { title: "Long-term waste, pests, vector control", status: "pending", priority: "P2", note: "Not yet drafted" },
    ],
  },
  {
    name: "Family & Special Needs",
    topics: [
      { title: "Disability, mobility, sensory, caregiver needs", status: "verified", priority: "P1", note: "Red Cross + Ready.gov" },
      { title: "Power-dependent medical equipment failure plan", status: "partial", priority: "P0", note: "" },
      { title: "Children in emergencies (age-appropriate prep)", status: "new", priority: "P2", note: "" },
      { title: "Elderly-specific emergency needs", status: "verified", priority: "P2", note: "CDC + Administration for Community Living" },
      { title: "Pregnancy considerations across scenarios", status: "partial", priority: "P1", note: "" },
      { title: "Psychological first aid and grief support", status: "verified", priority: "P2", note: "SAMHSA + Disaster Distress Helpline" },
      { title: "Helping children cope with disaster stress", status: "verified", priority: "P2", note: "CDC + American Red Cross" },
      { title: "Family Circle shared plan and permissions", status: "verified", priority: "P3", note: "App feature" },
      { title: "Medication continuity plan for dependents", status: "partial", priority: "P2", note: "" },
    ],
  },
  {
    name: "Inventory & Supplies",
    note: "Feature design exists; none of the tracking screens are built yet.",
    topics: [
      { title: "Food inventory (item/qty/calories/expiration/location)", status: "partial", priority: "P2", note: "Spec exists" },
      { title: "Water inventory and treatment supplies", status: "partial", priority: "P0", note: "Spec exists" },
      { title: "Medical/prescription/OTC inventory and expirations", status: "partial", priority: "P0", note: "Spec exists" },
      { title: "Power inventory (batteries/banks/solar/fuel)", status: "partial", priority: "P1", note: "Spec exists" },
      { title: "Tools and repair-supply inventory", status: "partial", priority: "P2", note: "Spec exists" },
      { title: "Pet-supply inventory", status: "partial", priority: "P2", note: "Spec exists" },
      { title: "Hygiene-supply inventory", status: "partial", priority: "P2", note: "Spec exists" },
      { title: "Emergency-document inventory", status: "partial", priority: "P2", note: "" },
      { title: "Fuel inventory", status: "partial", priority: "P1", note: "Spec exists" },
      { title: "Calculated days-of-water/food remaining", status: "partial", priority: "P2", note: "Spec exists" },
      { title: "Expiring-soon and missing-supplies alerts", status: "partial", priority: "P2", note: "Spec exists" },
    ],
  },
  {
    name: "Preparedness Plans",
    note: "Meant to become checklists generated from the underlying content.",
    topics: [
      { title: "Home fire escape plan", status: "partial", priority: "P1", note: "" },
      { title: "Tornado plan", status: "partial", priority: "P1", note: "" },
      { title: "Hurricane plan", status: "partial", priority: "P1", note: "" },
      { title: "Flood evacuation plan", status: "pending", priority: "P1", note: "" },
      { title: "Wildfire evacuation plan", status: "pending", priority: "P1", note: "" },
      { title: "Power outage plan", status: "partial", priority: "P2", note: "" },
      { title: "Winter storm plan", status: "pending", priority: "P1", note: "" },
      { title: "Medical emergency plan (household-specific)", status: "pending", priority: "P1", note: "" },
      { title: "Pet evacuation plan", status: "partial", priority: "P2", note: "" },
      { title: "Family separation / reunification plan", status: "pending", priority: "P1", note: "" },
      { title: "Bug-out / evacuation plan (general)", status: "partial", priority: "P1", note: "" },
      { title: "Shelter-in-place plan", status: "partial", priority: "P1", note: "" },
    ],
  },
  {
    name: "Reference Library",
    topics: [
      { title: "Longer-form recovery manuals", status: "partial", priority: "P2", note: "Flood/wildfire reentry, utility restoration" },
      { title: "Foundational source bibliography", status: "verified", priority: "P3", note: "" },
      { title: "Research and Evidence Standard (the rulebook)", status: "verified", priority: "P3", note: "" },
      { title: "Claim Verification Ledger and Publication Gate", status: "verified", priority: "P3", note: "" },
      { title: "Master Scenario Coverage Tracker (historical snapshot)", status: "verified", priority: "P3", note: "" },
      { title: "App engineering readiness checklist", status: "pending", priority: "P2", note: "" },
      { title: "Military/field-manual-derived survival-kit lessons", status: "partial", priority: "P3", note: "" },
      { title: "Community after-action lessons from real outages/storms", status: "partial", priority: "P3", note: "" },
    ],
  },
];
